# Generated by Django 6.0.3 on 2026-03-17 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('blog', 'Blog Post'), ('news', 'News Article'), ('howto', 'How-to Guide'), ('listicle', 'Listicle'), ('comparison', 'Comparison Article'), ('youtube', 'YouTube Video Article')], max_length=20)),
                ('prompt_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('keywords', models.JSONField(default=list)),
                ('primary_keyword', models.CharField(blank=True, max_length=100)),
                ('secondary_keywords', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Ready for Review'), ('approved', 'Approved'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('reading_time', models.IntegerField(default=0)),
                ('youtube_url', models.URLField(blank=True)),
                ('featured_image_url', models.URLField(blank=True)),
                ('internal_links', models.JSONField(default=list)),
                ('external_links', models.JSONField(default=list)),
                ('schema_markup', models.TextField(blank=True)),
                ('seo_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.contenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('anchor_text', models.CharField(max_length=200)),
                ('target_domain', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('outreach', 'Outreach Sent'), ('published', 'Published'), ('rejected', 'Rejected')], default='planned', max_length=20)),
                ('domain_authority', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.article')),
            ],
        ),
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_keywords', models.JSONField(default=list)),
                ('content_pillars', models.JSONField(default=list)),
                ('monthly_topics', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generator.article')),
            ],
        ),
    ]
