# Generated by Django 6.0.3 on 2026-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='primary_keyword',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Ready for Review'), ('approved', 'Approved'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='backlink',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('outreach', 'Outreach Sent'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='backlink',
            name='target_domain',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='backlink',
            name='target_url',
            field=models.URLField(db_index=True),
        ),
    ]
