# Generated by Django 6.0.3 on 2026-03-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_article_primary_keyword_alter_article_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('outreach', 'Outreach Sent'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=20)),
                ('domain_authority', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('backlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.backlink')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['backlink', '-recorded_at'], name='generator_b_backlin_5ff203_idx')],
            },
        ),
    ]
