# Generated by Django 4.2.29 on 2026-03-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemPerformanceLog',
        ),
        migrations.DeleteModel(
            name='TaskRetryLog',
        ),
        migrations.RemoveField(
            model_name='apierrorslog',
            name='stack_trace',
        ),
    ]
