# Generated by Django 6.0.3 on 2026-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analytics_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
