# Generated by Django 4.2.29 on 2026-03-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_cache_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='projects_pr_user_id_3cbd31_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['url', 'user'], name='projects_pr_url_ba15a4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['cache_expires_at'], name='projects_pr_cache_e_21d12c_idx'),
        ),
    ]
