# Generated by Django 4.2.29 on 2026-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_projects_pr_user_id_3cbd31_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='serp_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
