export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          "inverse-on-surface": "#f1f0f4",
          "on-error": "#ffffff",
          "primary-fixed": "#e0e6ff",
          "secondary": "#5d5697",
          "on-surface-variant": "#474555",
          "primary": "#2962ff",
          "on-primary": "#ffffff",
          "background": "#faf9fd",
          "on-secondary-fixed": "#190f50",
          "inverse-surface": "#2f3033",
          "on-primary-fixed-variant": "#3f23c5",
          "secondary-fixed-dim": "#c6bfff",
          "surface-container": "#eeedf1",
          "primary-container": "#1c4ede",
          "on-secondary-fixed-variant": "#453e7e",
          "surface-tint": "#2962ff",
          "tertiary-fixed-dim": "#ffb68e",
          "surface-container-lowest": "#ffffff",
          "on-tertiary-container": "#ffd5c0",
          "on-error-container": "#93000a",
          "tertiary": "#7b3500",
          "on-secondary-container": "#4b4584",
          "secondary-fixed": "#e4dfff",
          "surface-container-low": "#f4f3f7",
          "on-secondary": "#ffffff",
          "tertiary-container": "#a04800",
          "inverse-primary": "#c6bfff",
          "outline-variant": "#c8c4d7",
          "on-background": "#1a1c1e",
          "surface-variant": "#e3e2e6",
          "error-container": "#ffdad6",
          "outline": "#787586",
          "surface-container-high": "#e8e8ec",
          "primary-fixed-dim": "#c6bfff",
          "surface": "#faf9fd",
          "surface-dim": "#dad9dd",
          "on-primary-fixed": "#160066",
          "on-surface": "#1a1c1e",
          "on-tertiary-fixed-variant": "#763300",
          "tertiary-fixed": "#ffdbc9",
          "surface-container-highest": "#e3e2e6",
          "on-tertiary-fixed": "#331200",
          "surface-bright": "#faf9fd",
          "error": "#ba1a1a",
          "on-tertiary": "#ffffff",
          "secondary-container": "#bdb6fe",
          "on-primary-container": "#dfdaff"
        },
        fontFamily: {
          "headline": ["Plus Jakarta Sans"],
          "body": ["Plus Jakarta Sans"],
          "label": ["Plus Jakarta Sans"]
        },
        borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
      },
    },
    plugins: [
        require('@tailwindcss/container-queries'),
    ],
  };
