# Generated by Django 6.0.3 on 2026-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_seoaudithistory'),
        ('projects', '0004_project_analytics_cache'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seoaudithistory',
            index=models.Index(fields=['project', '-created_at'], name='audit_seoau_project_50af07_idx'),
        ),
    ]
