# Generated by Django 4.2.29 on 2026-03-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_seoaudithistory_full_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoreport',
            options={'ordering': ['-created_at']},
        ),
    ]
