# Generated by Django 6.0.3 on 2026-03-18 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('projects', '0003_alter_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('intent_type', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('navigational', 'Navigational'), ('transactional', 'Transactional')], default='informational', max_length=20)),
                ('difficulty_score', models.IntegerField(default=0)),
                ('search_volume', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
