# Generated by Django 6.0.3 on 2026-03-18 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keyword'),
        ('projects', '0003_alter_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_position', models.IntegerField(blank=True, null=True)),
                ('search_volume', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keyword')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
