# Generated by Django 6.0.3 on 2026-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_keywordtrend'),
        ('projects', '0004_project_analytics_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='competitor_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='domain_authority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='keyword_gaps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='keyword',
            name='cpc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='keyword',
            name='serp_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='keyword',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['project', 'keyword'], name='keywords_co_project_23aa76_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['project', 'keyword'], name='keywords_ke_project_0e6062_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordtrend',
            index=models.Index(fields=['keyword', '-recorded_at'], name='keywords_ke_keyword_c714ce_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordtrend',
            index=models.Index(fields=['project', '-recorded_at'], name='keywords_ke_project_24735f_idx'),
        ),
    ]
