# Generated by Django 4.2.29 on 2026-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_profile_and_serp_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_calls_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_received_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Reason for disabling the account', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='websites_searched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
